spring.application.name=CyberWebApp
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cyberweb
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Protocol Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thientq.odin@gmail.com
spring.mail.password=fbub rhsk csfl thpq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true